### ISSUE TITLE
tis 브랜치에 0.17.0까지의 기능이 포함되도록 작업

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto-client#115]
## 배경

- giganto-client 0.17.0 의 변경사항을 url-collector에서 사용하기 위해서 해당 작업이 필요합니다.
- current tis version : 0.15.2+tis.0.0.1
- target next tis version : 0.17.0+tis.0.1.0

### Task To do
- [x] 0.15.2+tis.0.0.1 가 태깅되었던 브랜치의 커밋과 히스토리를 보존하기 위해 기존 `tis` 브랜치를 `archive/0.15.2+tis.0.0.1` 으로 rename
- [x] 0.17.0 에서 `tis` 브랜치 다시 신규 생성
- [x] 0.17.0을 베이스로 하는  0.17.0+tis.0.1.0-alpha.1 생성하여서 PR

**Comment by sophie-cluml** [comment]
- 아카이빙한 브랜치 : https://github.com/aicers/giganto-client/tree/archive/0.15.2%2Btis.0.0.1
- 0.17.0 기반 `tis` 브랜치 : https://github.com/aicers/giganto-client/tree/tis

**Comment by sophie-cluml** [comment]
브랜치에 대한 PR 머지는 자동으로 issue를 close하지 못하므로, 수동으로 닫습니다.
